name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required to push to branches like 'documentation'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs  # Update if your docusaurus project is in a different folder

      - name: Build Docusaurus site
        run: npm run build
        working-directory: ./docs  # Update if needed

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build  # Path to the build output
          publish_branch: documentation
          force_orphan: true
